### ISSUE TITLE
model weights url error 403

### ISSUE THREAD

**Issue by mhj112358** [gvisani/Holographic-VAE#1]
Hi guys, is there a typo on the url for the model weights? We could not download the pre-trained model weights running download_pretrained_models.py

**Comment by gvisani** [comment]
The url seems to work on our end. Did you try opening the link manually, say, on Chrome or Safari?

I am not aware of reasons why one might get a 403-Forbidden error from opening figshare link... perhaps geographical restrictions? I will look more into it.

In the meantime, if the problem persists, feel free to reach out to me via email at gvisan01@cs.washington.edu and I can share the model in an alternative way.

**Comment by mhj112358** [comment]
It turns out to be geographical restriction somewhere indeed. It is resolved after reconfiguring my vpn. 

Thank you very much and wish you a great day ahead.

**Comment by gvisani** [comment]
Great to hear it's resolved! I'll add a warning to the readme
